Algoritmo "funções_aritmetricas_pratica01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/06/2026
Var
   angulo, Seno: Real


Inicio
   Escreva("Informe um angulo: ")
   Leia(angulo)
   Seno <- Sen(GraupRad(angulo))
   
   Escreva("O seno de", angulo, " é igual a", Seno)


Fimalgoritmo