Algoritmo "funções_aritmeticas_exemplo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/06/2026
Var
   //A: Inteiro
    A: Real

Inicio
     // A <- Abs(-50)
     
     // A <- Exp(9, 5)
     
     //A <- RaizQ(81)
     
     //A <- Int(RaizQ(90))
     
     //A <- GraupRad(90)
     
     A <- Sen(GraupRad(90))

     Escreva(A)


Fimalgoritmo