Algoritmo "Pratica_02_Operadores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/06/2026
Var
   N1, N2: Inteiro
   Media: Real

Inicio
      Escreva("Insira um numero: ")
      Leia(N1)
      
      Escreva("Insira outro numero: ")
      Leia(N2)

      Media <- (N1 + N2) / 2
      
      Escreva("A media entre",N1, " e",N2, " e igual a", Media)

Fimalgoritmo