Algoritmo "pratica_03_operadores_alteração"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/06/2026
Var
   N1, N2: Inteiro
   Media: Real


Inicio
      Escreva("Insira o primeiro numero:")
      Leia(N1)
      
      Escreva("Insira o segundo numero:")
      Leia(N2)
      
      Media <- (N1 + N2) / 2
      
      Escreva("A media entre", N1, "e", N2, "é igual a", Media)


Fimalgoritmo