Algoritmo "EXERCICIO_PRATICO01_FUNCOES_SOMAR_DOIS_NUMEROS"
// Data atual  : 01/07/2026
Var
   Valor1, Valor2, S: Inteiro

Funcao Soma(X, Y: Inteiro): Inteiro
Inicio
   Retorne x + y
FimFuncao

Inicio
   Escreva("Insira o primeiro valor: ")
   Leia(Valor1)

   Escreva("Insira o segundo valor: ")
   Leia(Valor2)

   S <- Soma(Valor1, Valor2)

   Escreva("A soma entre", Valor1, "e ", Valor2," e igual a ",S)


Fimalgoritmo