Algoritmo "Exercicio_Pratico02_Contagem_1_ate_10_com_repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/06/2026
Var
   contador: Inteiro


Inicio
      contador <- 1
      
      Repita
            Escreva(contador)
            contador <- contador + 1
      Ate(contador > 10)


Fimalgoritmo