Algoritmo "comando_entrada_exemplo_1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/06/2026
Var
   msg: caractere


Inicio
//Alternativa 1)
     // Escreval("Olá, mundo!")
     //Escreva("Ups pareçe que me livrei da maldição!")
//Alternativa 2)
     msg <- "Olá, mundo!"
     Escreva("Mensagem: ",msg)
Fimalgoritmo