Algoritmo "EXERCICIO_PRATICO01_CONTAR_10ATE0"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/06/2026
Var
   contador: Inteiro


Inicio
      contador <- 10

      Enquanto ( contador >= 0) faca
          EscrevaL(contador)
          contador <- contador - 1
      FimEnquanto
      Escreval("Terminei de contar!")
Fimalgoritmo