Algoritmo "EXERCICIO_PRATICO01_CONTAR_0ATE10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/06/2026
Var
   contador: Inteiro


Inicio
      contador <- 0
      
      Enquanto ( contador <= 10) faca
          EscrevaL(contador)
          contador <- contador + 1
      FimEnquanto
      Escreval("Terminei de contar!")
Fimalgoritmo