Algoritmo "EXERCICIO_PRATICO01_PROCEDIMENTO_SOMA_DE_VALORES"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/07/2026
Var
   valor_x, valor_y: Inteiro

Procedimento Soma(A,B: Inteiro)
Inicio
      Escreval("Recebi o valor ", A)
      Escreval("Recebi o valor ", B)
      Escreval("A soma entre os dois e", A + B)
FimProcedimento

Inicio
      valor_x <- 5
      valor_y <- 3
      
      Soma(valor_x, valor_y)
Fimalgoritmo